import {SOURCE_APPLICATION, SOURCE_APPLICATION_VERSION, VERSION, SERVICE_USER_ID, } from "./env";

const API_ROOT = "https://termhub.azurewebsites.net";

export { API_ROOT, SOURCE_APPLICATION, SOURCE_APPLICATION_VERSION, VERSION, SERVICE_USER_ID, };
