/*
TODO: Refactor & add more test cases:
  [Frontend functional / unit tests #701](https://github.com/jhu-bids/TermHub/issues/701)

### Definitions
- **Test targets**: Specific functionality we're testing, e.g. a single function.
- **Test cases**: Ambiguous. Could be (a) the csets for "test inputs", or (b) a single executable unit test / test case
w/in the given framework (combo of "test input" x "test target").
 */
import {test, expect} from '@jest/globals';

import {GraphContainer, makeGraph} from "./state/GraphState";


// UTILS
/* Used to convert input to be same as graphology serialization (all strings). */
function convertToArrayOfStrings(matrix) {
  var stringMatrix = [];
  for (var i = 0; i < matrix.length; i++) {
    var stringRow = [];
    for (var j = 0; j < matrix[i].length; j++) {
      stringRow.push(matrix[i][j].toString());
    }
    stringMatrix.push(stringRow);
  }
  return stringMatrix;
}

// VARS
// diagramCase: last copied from test_graph.py test_get_missing_in_between_nodes(): 2024/02/11
let diagramCase = [
    [2, 1],
    ['root', '2p1'], ['2p1', 2], ['root', '2p2'], ['2p2', 2], ['root', 'cloud'],
    [4, 3],
    [5, 4],
    [7, 5],
    [8, 7],
    ['cloud', 8],
    [2, 8],
    [6, 5],
    ['cloud', 6],
    [10, 9],
    [4, 10],
    [10, 12],
    [11, 10],
    [6, 11],
    [11, 13],
    [15, 14],
    ['cloud', 15],
    [16, 21],
    [17, 16],
    [6, 17],
    [18, 17],
    [15, 18],
    [20, 16],
    ['cloud', 20],
    [22, 23],
    [19, 22],
    [20, 19],
];
diagramCase = convertToArrayOfStrings(diagramCase);
// const singleSmallFromConceptGraphEndpoint = {
// 	"edges":[[4174977,380096],[4034964,4029423],[4311708,376112],[4102176,35625722],[442793,443767],[442793,4034964],[376112,4044392],[380096,4210128],[4210128,4161671],[4044391,4311708],[4129519,43531010],[4029423,4016047],[443767,4102176],[443767,4174977],[443767,4224419],[35625722,35625724]],
// 	"concept_ids":[4174977,43531010,4161671,4327944,4221962,4237068,4034962,4034964,4311708,4294429,4102176,45766050,4224419,442793,4016047,376112,35626038,35626039,4162239,36674752,380096,43022019,4252356,4210128,44833365,3172958,4270049,4044391,4044392,4129519,4029423,4129524,4129525,443767,35625722,35625724],
// 	"filled_gaps":[380096,4210128,376112,443767,35625722,4311708,4029423],
// 	"missing_from_graph":[4252356,44833365],
// 	"hidden_by_vocab":{},
// 	"nonstandard_concepts_hidden":[]
// };
const singleSmallGraphContainerGraphData = {
    "edges": [
        [
            4174977,
            380096
        ],
        [
            4034964,
            4029423
        ],
        [
            4311708,
            376112
        ],
        [
            4102176,
            35625722
        ],
        [
            442793,
            443767
        ],
        [
            442793,
            4034964
        ],
        [
            376112,
            4044392
        ],
        [
            380096,
            4210128
        ],
        [
            4210128,
            4161671
        ],
        [
            4044391,
            4311708
        ],
        [
            4129519,
            43531010
        ],
        [
            4029423,
            4016047
        ],
        [
            443767,
            4102176
        ],
        [
            443767,
            4174977
        ],
        [
            443767,
            4224419
        ],
        [
            35625722,
            35625724
        ]
    ],
    "concept_ids": [
        4174977,
        43531010,
        4161671,
        4327944,
        4221962,
        4237068,
        4034962,
        4034964,
        4311708,
        4294429,
        4102176,
        45766050,
        4224419,
        442793,
        4016047,
        376112,
        35626038,
        35626039,
        4162239,
        36674752,
        380096,
        43022019,
        4252356,
        4210128,
        44833365,
        3172958,
        4270049,
        4044391,
        4044392,
        4129519,
        4029423,
        4129524,
        4129525,
        443767,
        35625722,
        35625724
    ],
    "filled_gaps": [
        380096,
        4210128,
        376112,
        443767,
        35625722,
        4311708,
        4029423
    ],
    "missing_from_graph": [
        4252356,
        44833365
    ],
    "hidden_by_vocab": {},
    "nonstandard_concepts_hidden": [],
    "concepts": [
        {
            "concept_id": 376112,
            "concept_name": "Polyneuropathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "49455004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 322569,
            "distinct_person_cnt": "50865",
            "status": ""
        },
        {
            "concept_id": 380096,
            "concept_name": "Proliferative retinopathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "59276001",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 76499,
            "distinct_person_cnt": "8684",
            "status": ""
        },
        {
            "concept_id": 442793,
            "concept_name": "Complication due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "74627003",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 6021141,
            "distinct_person_cnt": "652425",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 443767,
            "concept_name": "Disorder of eye due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "25093002",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 166577,
            "distinct_person_cnt": "23921",
            "status": ""
        },
        {
            "concept_id": 3172958,
            "concept_name": "Diabetic ulcer of right wrist",
            "domain_id": "Condition",
            "vocabulary_id": "Nebraska Lexicon",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "20980001000004109",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4016047,
            "concept_name": "Loss of hypoglycemic warning due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "170766006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4029423,
            "concept_name": "Hypoglycemia due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237633009",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 19846,
            "distinct_person_cnt": "6412",
            "status": ""
        },
        {
            "concept_id": 4034962,
            "concept_name": "Hyperproinsulinemia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237613005",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4034964,
            "concept_name": "Abnormal metabolic state due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237620003",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 359,
            "distinct_person_cnt": "80",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4044391,
            "concept_name": "Neuropathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "230572002",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 87553,
            "distinct_person_cnt": "16134",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4044392,
            "concept_name": "Chronic painful polyneuropathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "230575000",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4102176,
            "concept_name": "Iritis due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "193489006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4129519,
            "concept_name": "Pregnancy and type 2 diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237627000",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 2886,
            "distinct_person_cnt": "379",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4129524,
            "concept_name": "Insulin resistance - type A",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237651005",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4129525,
            "concept_name": "Insulin resistance - type B",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237652003",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4161671,
            "concept_name": "Non-high-risk proliferative retinopathy with no macular edema due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "399870006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4162239,
            "concept_name": "Somogyi phenomenon",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "398140007",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4174977,
            "concept_name": "Retinopathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "4855003",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 28120,
            "distinct_person_cnt": "8843",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4210128,
            "concept_name": "Non-high-risk proliferative retinopathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "312906006",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "status": ""
        },
        {
            "concept_id": 4221962,
            "concept_name": "Very severe nonproliferative retinopathy without macular edema due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "399863006",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4224419,
            "concept_name": "Disorder of eye due to malnutrition related diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "421256007",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4237068,
            "concept_name": "Diabetes mellitus due to structurally abnormal insulin",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "91352004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 146,
            "distinct_person_cnt": "25",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4252356,
            "concept_name": "O/E - left eye proliferative diabetic retinopathy",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": null,
            "concept_code": "408414006",
            "invalid_reason": "D",
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 2183,
            "distinct_person_cnt": "374",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4270049,
            "concept_name": "Nodular type diabetic glomerulosclerosis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "63510008",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4294429,
            "concept_name": "Wet gangrene of foot due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "402864004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 107,
            "distinct_person_cnt": "39",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4311708,
            "concept_name": "Diabetic peripheral neuropathy",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "424736006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 4260,
            "distinct_person_cnt": "1352",
            "status": ""
        },
        {
            "concept_id": 4327944,
            "concept_name": "Malnutrition related diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "75524006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 26,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 35625722,
            "concept_name": "Iritis of right eye due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "768797001",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "status": ""
        },
        {
            "concept_id": 35625724,
            "concept_name": "Bilateral iritis due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "768799003",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 35626038,
            "concept_name": "Mild nonproliferative retinopathy of right eye due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "769183005",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 16773,
            "distinct_person_cnt": "4777",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 35626039,
            "concept_name": "Mild nonproliferative retinopathy of left eye due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "769184004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 15932,
            "distinct_person_cnt": "4579",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 36674752,
            "concept_name": "Microaneurysm of right retinal artery due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "770581008",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 43022019,
            "concept_name": "On subcutaneous insulin for diabetes mellitus",
            "domain_id": "Observation",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "473189005",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 43531010,
            "concept_name": "Pre-existing type 2 diabetes mellitus in pregnancy",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "609567009",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 389942,
            "distinct_person_cnt": "24676",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 44833365,
            "concept_name": "Diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "ICD9CM",
            "concept_class_id": "3-dig nonbill code",
            "standard_concept": null,
            "concept_code": "250",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 45766050,
            "concept_name": "Diabetes mellitus in remission",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "703136005",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        }
    ]
};
const manySmallGraphContainerGraphData = {
    "edges": [
        [
            77317,
            46269848
        ],
        [
            4046355,
            4046356
        ],
        [
            194077,
            78799
        ],
        [
            4102176,
            35625722
        ],
        [
            40482865,
            40481367
        ],
        [
            4131915,
            4271197
        ],
        [
            4131917,
            4271197
        ],
        [
            40479837,
            77317
        ],
        [
            40479837,
            194077
        ],
        [
            40479837,
            4031048
        ],
        [
            40479837,
            4301738
        ],
        [
            40479837,
            40482241
        ],
        [
            40479839,
            40482241
        ],
        [
            4044391,
            4311708
        ],
        [
            4174977,
            376683
        ],
        [
            4311708,
            376112
        ],
        [
            37311673,
            4162239
        ],
        [
            4129519,
            43531010
        ],
        [
            35625722,
            35625724
        ],
        [
            4269871,
            4221962
        ],
        [
            376112,
            4044392
        ],
        [
            376683,
            4269871
        ],
        [
            4160887,
            36713763
        ],
        [
            443767,
            4102176
        ],
        [
            443767,
            4174977
        ],
        [
            443767,
            4224419
        ],
        [
            76685,
            81400
        ],
        [
            76685,
            4043730
        ],
        [
            76685,
            4045731
        ],
        [
            76685,
            4046355
        ],
        [
            76685,
            4048782
        ],
        [
            76685,
            4135454
        ],
        [
            76685,
            4204694
        ],
        [
            76685,
            4215003
        ],
        [
            76685,
            43531560
        ],
        [
            76685,
            43531561
        ],
        [
            4034964,
            37311673
        ],
        [
            442793,
            443767
        ],
        [
            442793,
            4034964
        ],
        [
            441269,
            4131915
        ],
        [
            441269,
            4131917
        ],
        [
            441269,
            4146936
        ],
        [
            441269,
            4160887
        ],
        [
            441269,
            4219853
        ],
        [
            441269,
            36674478
        ],
        [
            40482241,
            46269838
        ],
        [
            4219853,
            436956
        ],
        [
            4219853,
            36713763
        ],
        [
            81893,
            4029372
        ],
        [
            81893,
            4086978
        ],
        [
            81893,
            4187900
        ],
        [
            81893,
            40479837
        ],
        [
            81893,
            40479839
        ],
        [
            81893,
            40482865
        ],
        [
            81893,
            44783784
        ],
        [
            81893,
            46269951
        ],
        [
            4209139,
            4269919
        ],
        [
            46269951,
            46269838
        ],
        [
            46269951,
            46269848
        ]
    ],
    "concept_ids": [
        77317,
        4327944,
        4221962,
        4046355,
        4046356,
        194077,
        4135454,
        4102176,
        40482865,
        35626038,
        35626039,
        4031048,
        4131915,
        4131917,
        44833365,
        40481367,
        4271197,
        3172958,
        40479839,
        40479837,
        4044391,
        4044392,
        4174977,
        4161671,
        4204694,
        4311708,
        44783784,
        37311673,
        4162239,
        36674752,
        4086978,
        43022019,
        4252356,
        4215003,
        436956,
        4129519,
        4129524,
        4129525,
        4146936,
        35625722,
        4187900,
        35625724,
        43531010,
        4237068,
        4294429,
        36713763,
        43531560,
        43531561,
        37117740,
        4269871,
        376112,
        4269919,
        376683,
        4160887,
        443767,
        37116298,
        37116300,
        37116301,
        46269838,
        4048782,
        46269840,
        46269841,
        4034962,
        76685,
        4034964,
        46269848,
        46269850,
        46269851,
        45766050,
        4045731,
        4224419,
        442793,
        4301738,
        36674478,
        4016047,
        441269,
        4029372,
        40482241,
        4219853,
        78799,
        4043730,
        4270049,
        81893,
        4215784,
        4209139,
        81400,
        46269951
    ],
    "filled_gaps": [
        376112,
        376683,
        443767,
        37311673,
        35625722,
        4131915,
        4311708,
        4269871
    ],
    "missing_from_graph": [
        4252356,
        44833365
    ],
    "hidden_by_vocab": {},
    "nonstandard_concepts_hidden": [],
    "concepts": [
        {
            "concept_id": 76685,
            "concept_name": "Myasthenia gravis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "91637004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 16301,
            "distinct_person_cnt": "1478",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 77317,
            "concept_name": "Chronic ulcerative rectosigmoiditis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "52506002",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 102651,
            "distinct_person_cnt": "12354",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 78799,
            "concept_name": "Chronic ulcerative ileocolitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "13470001",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 214,
            "distinct_person_cnt": "57",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 81400,
            "concept_name": "Neonatal myasthenia gravis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "82178003",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 191,
            "distinct_person_cnt": "36",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 81893,
            "concept_name": "Ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "64766004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 739356,
            "distinct_person_cnt": "87131",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 194077,
            "concept_name": "Chronic ulcerative enterocolitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "15342002",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 1902,
            "distinct_person_cnt": "526",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 376112,
            "concept_name": "Polyneuropathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "49455004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 322569,
            "distinct_person_cnt": "50865",
            "status": ""
        },
        {
            "concept_id": 376683,
            "concept_name": "Nonproliferative retinopathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "390834004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 33813,
            "distinct_person_cnt": "9108",
            "status": ""
        },
        {
            "concept_id": 436956,
            "concept_name": "Evans syndrome",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "75331009",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 29073,
            "distinct_person_cnt": "1242",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 441269,
            "concept_name": "Autoimmune hemolytic anemia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "413603009",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 236793,
            "distinct_person_cnt": "12270",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 442793,
            "concept_name": "Complication due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "74627003",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 6021141,
            "distinct_person_cnt": "652425",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 443767,
            "concept_name": "Disorder of eye due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "25093002",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 166577,
            "distinct_person_cnt": "23921",
            "status": ""
        },
        {
            "concept_id": 3172958,
            "concept_name": "Diabetic ulcer of right wrist",
            "domain_id": "Condition",
            "vocabulary_id": "Nebraska Lexicon",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "20980001000004109",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4016047,
            "concept_name": "Loss of hypoglycemic warning due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "170766006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4029372,
            "concept_name": "Acute ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "128600008",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 416,
            "distinct_person_cnt": "129",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4031048,
            "concept_name": "Severe chronic ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "14311001",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 36,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4034962,
            "concept_name": "Hyperproinsulinemia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237613005",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4034964,
            "concept_name": "Abnormal metabolic state due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237620003",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 359,
            "distinct_person_cnt": "80",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4043730,
            "concept_name": "Generalized myasthenia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "230686005",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 86,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4044391,
            "concept_name": "Neuropathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "230572002",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 87553,
            "distinct_person_cnt": "16134",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4044392,
            "concept_name": "Chronic painful polyneuropathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "230575000",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4045731,
            "concept_name": "Myasthenia gravis associated with thymoma",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "230685009",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 220,
            "distinct_person_cnt": "25",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4046355,
            "concept_name": "Genetically determined myasthenia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "230669004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 48,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4046356,
            "concept_name": "Congenital myasthenic syndrome",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "230672006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 2002,
            "distinct_person_cnt": "212",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4048782,
            "concept_name": "Ocular myasthenia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "230684008",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 588,
            "distinct_person_cnt": "135",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4086978,
            "concept_name": "Eosinophilic ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "24829000",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 63,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4102176,
            "concept_name": "Iritis due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "193489006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4129519,
            "concept_name": "Pregnancy and type 2 diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237627000",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 2886,
            "distinct_person_cnt": "379",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4129524,
            "concept_name": "Insulin resistance - type A",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237651005",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4129525,
            "concept_name": "Insulin resistance - type B",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "237652003",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4131915,
            "concept_name": "Primary (idiopathic) autoimmune hemolytic anemia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "127049002",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "status": ""
        },
        {
            "concept_id": 4131917,
            "concept_name": "Paroxysmal cold hemoglobinuria",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "127057004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4135454,
            "concept_name": "Myasthenia gravis, adult form",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "31839002",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 155,
            "distinct_person_cnt": "23",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4146936,
            "concept_name": "Drug-induced autoimmune hemolytic anemia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "309742004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 4793,
            "distinct_person_cnt": "1001",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4160887,
            "concept_name": "Cold autoimmune hemolytic anemia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "398937006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 31915,
            "distinct_person_cnt": "1819",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4161671,
            "concept_name": "Non-high-risk proliferative retinopathy with no macular edema due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "399870006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4162239,
            "concept_name": "Somogyi phenomenon",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "398140007",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4174977,
            "concept_name": "Retinopathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "4855003",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 28120,
            "distinct_person_cnt": "8843",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4187900,
            "concept_name": "Exacerbation of ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "414156000",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 74,
            "distinct_person_cnt": "40",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4204694,
            "concept_name": "Myasthenia gravis, juvenile form",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "55051001",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 35,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4209139,
            "concept_name": "Autoimmune hemolytic anemia due to IgG",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "5603006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 134,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4215003,
            "concept_name": "Myasthenic crisis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "80976008",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 427,
            "distinct_person_cnt": "114",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4215784,
            "concept_name": "Autoimmune hemolytic anemia due to IgM",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "71832003",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4219853,
            "concept_name": "Warm autoimmune hemolytic anemia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "3978000",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 27368,
            "distinct_person_cnt": "4226",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4221962,
            "concept_name": "Very severe nonproliferative retinopathy without macular edema due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "399863006",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4224419,
            "concept_name": "Disorder of eye due to malnutrition related diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "421256007",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4237068,
            "concept_name": "Diabetes mellitus due to structurally abnormal insulin",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "91352004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 146,
            "distinct_person_cnt": "25",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4252356,
            "concept_name": "O/E - left eye proliferative diabetic retinopathy",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": null,
            "concept_code": "408414006",
            "invalid_reason": "D",
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 2183,
            "distinct_person_cnt": "374",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4269871,
            "concept_name": "Very severe nonproliferative retinopathy due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "399876000",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "status": ""
        },
        {
            "concept_id": 4269919,
            "concept_name": "Autoimmune hemolytic anemia due to IgG plus complement",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "62609001",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 82,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4270049,
            "concept_name": "Nodular type diabetic glomerulosclerosis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "63510008",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4271197,
            "concept_name": "Idiopathic paroxysmal cold hemoglobinuria",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "62871001",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4294429,
            "concept_name": "Wet gangrene of foot due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "402864004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 107,
            "distinct_person_cnt": "39",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4301738,
            "concept_name": "Mild chronic ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "78324009",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 325,
            "distinct_person_cnt": "124",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 4311708,
            "concept_name": "Diabetic peripheral neuropathy",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "424736006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 4260,
            "distinct_person_cnt": "1352",
            "status": ""
        },
        {
            "concept_id": 4327944,
            "concept_name": "Malnutrition related diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "75524006",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 26,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 35625722,
            "concept_name": "Iritis of right eye due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "768797001",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "status": ""
        },
        {
            "concept_id": 35625724,
            "concept_name": "Bilateral iritis due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "768799003",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 35626038,
            "concept_name": "Mild nonproliferative retinopathy of right eye due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "769183005",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 16773,
            "distinct_person_cnt": "4777",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 35626039,
            "concept_name": "Mild nonproliferative retinopathy of left eye due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "769184004",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 15932,
            "distinct_person_cnt": "4579",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 36674478,
            "concept_name": "Neonatal autoimmune hemolytic anemia",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "774083009",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 36674752,
            "concept_name": "Microaneurysm of right retinal artery due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "770581008",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 36713763,
            "concept_name": "Autoimmune hemolytic anemia mixed type",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "718716008",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 1032,
            "distinct_person_cnt": "183",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 37116298,
            "concept_name": "Secondary autoimmune hemolytic anemia co-occurrent and due to lymphoproliferative disorder",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "732963000",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 164,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 37116300,
            "concept_name": "Secondary autoimmune hemolytic anemia co-occurrent and due to rheumatic disorder",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "732965007",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 37116301,
            "concept_name": "Secondary autoimmune hemolytic anemia co-occurrent and due to ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "732966008",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 37117740,
            "concept_name": "Secondary autoimmune hemolytic anemia co-occurrent and due to systemic lupus erythematosus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "732960002",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 62,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 37311673,
            "concept_name": "Hyperglycemia due to diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "822995009",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 7040,
            "distinct_person_cnt": "2172",
            "status": ""
        },
        {
            "concept_id": 40479837,
            "concept_name": "Chronic ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "444546002",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 25477,
            "distinct_person_cnt": "4389",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 40479839,
            "concept_name": "Ulcerative pancolitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "444548001",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 37690,
            "distinct_person_cnt": "3252",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 40481367,
            "concept_name": "Chronic left-sided ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "441971007",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 3915,
            "distinct_person_cnt": "880",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 40482241,
            "concept_name": "Chronic ulcerative pancolitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "442159003",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 585001,
            "distinct_person_cnt": "47011",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 40482865,
            "concept_name": "Left sided ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "445243001",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 68099,
            "distinct_person_cnt": "12596",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 43022019,
            "concept_name": "On subcutaneous insulin for diabetes mellitus",
            "domain_id": "Observation",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "473189005",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 43531010,
            "concept_name": "Pre-existing type 2 diabetes mellitus in pregnancy",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "609567009",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 389942,
            "distinct_person_cnt": "24676",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 43531560,
            "concept_name": "Myasthenia gravis with exacerbation",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "77461000119109",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 84770,
            "distinct_person_cnt": "5112",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 43531561,
            "concept_name": "Myasthenia gravis without exacerbation",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "77471000119103",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 537492,
            "distinct_person_cnt": "20455",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 44783784,
            "concept_name": "Ulcerative colitis in remission",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "697969008",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 35,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 44833365,
            "concept_name": "Diabetes mellitus",
            "domain_id": "Condition",
            "vocabulary_id": "ICD9CM",
            "concept_class_id": "3-dig nonbill code",
            "standard_concept": null,
            "concept_code": "250",
            "invalid_reason": null,
            "domain_cnt": 0,
            "domain": "",
            "total_cnt": 0,
            "distinct_person_cnt": "0",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 45766050,
            "concept_name": "Diabetes mellitus in remission",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "703136005",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 20,
            "distinct_person_cnt": "20",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 46269838,
            "concept_name": "Abscess of intestine co-occurrent and due to chronic ulcerative pancolitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "1085131000119105",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 2339,
            "distinct_person_cnt": "723",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 46269840,
            "concept_name": "Fistula of intestine due to chronic ulcerative pancolitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "1085151000119104",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 2673,
            "distinct_person_cnt": "455",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 46269841,
            "concept_name": "Rectal hemorrhage due to chronic ulcerative pancolitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "1085171000119108",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 200052,
            "distinct_person_cnt": "13051",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 46269848,
            "concept_name": "Abscess of intestine co-occurrent and due to chronic ulcerative rectosigmoiditis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "1085231000119100",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 800,
            "distinct_person_cnt": "200",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 46269850,
            "concept_name": "Fistula of large intestine due to chronic ulcerative rectosigmoiditis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "1085251000119106",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 552,
            "distinct_person_cnt": "106",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 46269851,
            "concept_name": "Rectal hemorrhage due to chronic ulcerative rectosigmoiditis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "1085271000119102",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 60946,
            "distinct_person_cnt": "5194",
            "isItem": true,
            "status": "Def"
        },
        {
            "concept_id": 46269951,
            "concept_name": "Abscess of intestine co-occurrent and due to ulcerative colitis",
            "domain_id": "Condition",
            "vocabulary_id": "SNOMED",
            "concept_class_id": "Clinical Finding",
            "standard_concept": "S",
            "concept_code": "1092841000119100",
            "invalid_reason": null,
            "domain_cnt": 1,
            "domain": "condition_occurrence",
            "total_cnt": 4696,
            "distinct_person_cnt": "1505",
            "isItem": true,
            "status": "Def"
        }
    ]
};

// TESTS
// TODO: What are some good assertions, given various inputs?
// - makeGraph()
test('test makeGraph() - diagram case', () => {
  const uniqueConcepts = [...new Set(diagramCase.flat())];
  const uniqueConceptObjs = uniqueConcepts.map(d => ({concept_id: d}));
  const [graph, nodes] = makeGraph(diagramCase, uniqueConceptObjs);
  
  // noinspection JSUnresolvedReference idkWhyUnresolved
  expect(graph.directedSize).toBe(32);
  expect(graph.nodes()).toStrictEqual(uniqueConcepts);
});

// TODO:
test('test makeGraph() - 1 cset "single small"', () => {
  console.log();
});

// TODO:
test('test makeGraph() - 2+ csets', () => {
  console.log();
});

// - roots, leaves
// todo?
// test('test roots, leaves - diagram case', () => {});

test('test roots, leaves - 1 cset "single small"', () => {
  const gc = new GraphContainer(singleSmallGraphContainerGraphData);
  expect(gc.roots).toStrictEqual(["442793", "4044391", "4129519", "isolated"]);
  expect(gc.leaves).toStrictEqual(["3172958", "4016047", "4034962", "4044392", "4129524", "4129525", "4161671", "4162239", "4221962", "4224419", "4237068", "4252356", "4270049", "4294429", "4327944", "35625724", "35626038", "35626039", "36674752", "43022019", "43531010", "44833365", "45766050"]);
});

test('test roots, leaves - 2+ csets', () => {
  const gc = new GraphContainer(manySmallGraphContainerGraphData);
  expect(gc.roots).toStrictEqual(["76685", "81893", "441269", "442793", "4044391", "4129519", "4209139", "isolated"]);
  expect(gc.leaves).toStrictEqual(["78799", "81400", "436956", "3172958", "4016047", "4029372", "4031048", "4034962", "4043730", "4044392", "4045731", "4046356", "4048782", "4086978", "4129524", "4129525", "4135454", "4146936", "4161671", "4162239", "4187900", "4204694", "4215003", "4215784", "4221962", "4224419", "4237068", "4252356", "4269919", "4270049", "4271197", "4294429", "4301738", "4327944", "35625724", "35626038", "35626039", "36674478", "36674752", "36713763", "37116298", "37116300", "37116301", "37117740", "40481367", "43022019", "43531010", "43531560", "43531561", "44783784", "44833365", "45766050", "46269838", "46269840", "46269841", "46269848", "46269850", "46269851"]);
});
